version: '3.8'

services:

  kinesalite:
    build:
      context: .
      dockerfile: ./kinesalite.dockerfile
    working_dir: /workspace/
    ports:
      - 4567:4567
    command: /bin/bash -c "kinesalite"

  consumer:
    build:
      context: .
      dockerfile: ./kinesis-consumer.dockerfile
    working_dir: /workspace/kinesis-consumer/
    depends_on:
      - kinesalite
    command: /bin/bash -c "sleep 3 && go run ./cmd/consumer/main.go --stream myStream --endpoint http://kinesalite:4567"

  producer:
    build:
      context: .
      dockerfile: ./kinesis-consumer.dockerfile
    working_dir: /workspace/kinesis-consumer/
    depends_on:
      - consumer
    command: /bin/bash -c "cat ./cmd/producer/users.txt | go run ./cmd/producer/main.go --stream myStream --endpoint http://kinesalite:4567"
